version: "2"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gomodguard # deprecated
    - interfacebloat
    - ireturn
    - maintidx
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - tagliatelle
    - testableexamples
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 140
      statements: 60
    gocognit:
      min-complexity: 40
    goconst:
      ignore-tests: true
    gocyclo:
      min-complexity: 40
    govet:
      disable:
        - composites
        - fieldalignment
      enable-all: true
    lll:
      line-length: 120
      tab-width: 4
    misspell:
      locale: US
    nestif:
      min-complexity: 7
    nolintlint:
      require-specific: true
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant # duplicate of goconst
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: exported
          disabled: true
        - name: function-result-limit
          arguments:
            - 4
        - name: function-length # duplicate of funlen
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: line-length-limit
          disabled: true # duplicate of lll
        - name: max-public-structs
          disabled: true
        - name: package-comments
          disabled: true
    sloglint:
      no-mixed-args: true
      kv-only: false
      attr-only: true
      static-msg: true
      no-raw-keys: false
      key-naming-case: snake
      args-on-sep-lines: true
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
    usetesting:
      context-background: true
      context-todo: true
      os-temp-dir: true
  exclusions:
    warn-unused: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/GolangUA/telegram-butler)
    gofumpt:
      extra-rules: true
