version: 3

silent: true

vars:
  GOLANGCI_LINT_VERSION: v2.12.2

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all

  pre-commit:
    desc: "Run formatters, linters, tests"
    cmds:
      - task: format
      - task: lint
      - task: test

  run:local:
    desc: "Run service locally"
    cmds:
      - go run -tags local ./cmd/telegram-butler/

  run:docker:
    desc: "Run service locally in Docker"
    cmds:
      - docker build -f Dockerfile.local -t telegram-butler:local .
      - docker run --rm --env-file .env -p 8080:8080 telegram-butler:local

  format:
    desc: "Run formatters"
    deps: [ install:lint ]
    aliases: [ fmt ]
    cmds:
      - echo "Running formatters..."
      - golangci-lint fmt
    sources:
      - ./**/*.go
      - go.mod
      - go.sum

  lint:
    desc: "Run golangci-lint"
    deps: [ install:lint ]
    cmds:
      - echo "Running linters..."
      - golangci-lint run
    sources:
      - .golangci.yaml
      - ./**/*.go
      - go.mod
      - go.sum

  lint:list:
    desc: "Run golangci-lint linters (print enabled & disabled linters)"
    deps: [ install:lint ]
    cmds:
      - golangci-lint linters

  test:
    desc: "Run tests"
    cmds:
      - echo "Running tests..."
      - mkdir -p bin
      - go test -coverprofile bin/cover.out ./...
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/cover.out

  test:cover:
    desc: "Run tests & show coverage"
    deps:
      - test
    cmds:
      - go tool cover -func bin/cover.out

  test:race:
    desc: "Run tests with a race flag"
    cmds:
      - go test -race -count=8 -failfast ./...

  install:
    desc: "Install all tools"
    deps:
      - install:lint

  install:lint:
    desc: "Install golangci-lint"
    cmds:
      - curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin {{.GOLANGCI_LINT_VERSION}}
    status:
      - command -v golangci-lint
